plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
dependencies {
    implementation project(':execution-core-spring-boot-starter')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}