plugins {
    id 'java-library'
}

dependencies {
    // Core Domain Module
    implementation project(':execution-core')

    // Storage Adapter Modules
    // Provides class references (LettuceAtomicStore, JedisAtomicStore, SpringDataRedisAtomicStore)
    // needed by ExecutionStorageAutoConfiguration.
    implementation project(':execution-storage-lettuce')
    implementation project(':execution-storage-jedis')
    implementation project(':execution-storage-springdata')

    // External Redis Drivers declared as compileOnly for @ConditionalOnClass inspection
    compileOnly 'io.lettuce:lettuce-core:6.3.2.RELEASE'
    compileOnly 'redis.clients:jedis:5.1.0'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-redis:3.2.0'
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

    // Spring Boot Infrastructure
    implementation 'org.springframework.boot:spring-boot-starter-aop:3.2.0'
    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.2.0'

    // Generates metadata for application.yml auto-complete
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor:3.2.0'


    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}